# Generated by Django 4.2 on 2025-01-11 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='Trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.trainer'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('P', 'PLanta'), ('T', 'Tierra'), ('F', 'Fuego'), ('A', 'Agua'), ('L', 'Lagartija'), ('E', 'Electrico')], max_length=30),
        ),
    ]
