# Generated by Django 4.2 on 2025-01-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_pokemon_trainer_alter_pokemon_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='Trainer',
            new_name='trainer',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pokemons/'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('P', 'Planta'), ('F', 'Fuego'), ('L', 'Lagartija'), ('T', 'Tierra'), ('E', 'Eléctrico')], max_length=30),
        ),
    ]
